services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - gateway-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - gateway-network

volumes:
  redis_data:

networks:
  gateway-network:
    driver: bridge
